In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
x = np.array([1,2,3,4,5])
x_list = [1,2,3,4,5]
y = np.arange(10,15)

In [8]:
x*2

array([ 2,  4,  6,  8, 10])

In [9]:
x_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [10]:
print(y)

[10 11 12 13 14]


In [11]:
x + y

array([11, 13, 15, 17, 19])

In [12]:
print(x,y)

[1 2 3 4 5] [10 11 12 13 14]


In [15]:
z = np.array([[1,2],[3,4]])
print(z)

[[1 2]
 [3 4]]
